name: Initiate SOOS Scan
# Events required to engage workflow (add/edit this list as needed)
on: 
  push:
    branches: 
      - main 
    paths:
      - '*.json'
jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS Scan
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-ci-analysis-github-actions@main
      with:
        project_name: "peijin_testing_github_actions_again"
        directories_to_exclude: "IgnoreMe"
        files_to_exclude: ""
        base_uri: "https://dev-api.soos.io/api/"
        analysis_result_max_wait: 300
        analysis_result_polling_interval: 10
        debug_print_variables: true
        
      env:
        # Visit https://soos.io to get the required tokens to leverage SOOS scanning/analysis services
        SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
        SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}

name: DAST shit bro 
on: [push]

jobs:
  soos_dast_analysis_example:
    name: SOOS DAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/dast@v1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "DAST-GitHub-Action-Test"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "https://www.example.com/"
